services:

  mysql-container:
    image: "mysql:5.7-debian"
    container_name: mysql-container
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      - MYSQL_ROOT_PASSWORD=abc


  blog_app:
    build: ./ 
    container_name: blog_app
    volumes:
      - ./config.json:/app/config.json


  nginx-container:
    image: nginx:alpine
    container_name: nginx-container
    depends_on: 
      - mysql-container
      - blog_app
    ports:
      - 8080:80
    volumes:
      - ./config/flask.conf:/etc/nginx/conf.d/default.conf


volumes:
  mysql-data:
